---
title: 'Performance Comparison: Data.table in R and Pandas in Python'
author: "Doris Amoakohene"
date: "`r Sys.Date()`"
output: html_document
---



## Libraries

```{r setup,warning=FALSE,message=FALSE}
library(data.table)
library(reshape2)
library(atime)
library(ggplot2)
library(reticulate)
use_python("C:/Users/amoak/AppData/Local/Programs/Python/Python312/python.exe") #If you want to reproduce, please change to the path of python on your computer.
virtualenv_create("fm-proj")
use_virtualenv("fm-proj", required = F)

```


```{python}
file_path = 'data.csv'
```


# Example 1:  Writing a CSV File with data.table::fwrite() and pandas::to_csv()


## Comparison code

```{r,warning=FALSE,message=FALSE}
write.colors <- c(
  "data.table::fwrite" = "#D6604D",
  "pandas::to_csv" = "#BF812D"
)
file_path = 'data.csv'
n.rows <- 100
seconds.limit <- 10
atime.write.vary.cols <- atime::atime(
  N = as.integer(10^seq(2, 10, by = 0.2)),
  setup = {
    set.seed(1)
    input.vec <- rnorm(n.rows * N)
    input.mat <- matrix(input.vec, n.rows, N)
    input.df <- data.frame(input.mat) 
    pd <- import("pandas")
    input_df_pd <- r_to_py(input.df)
  },
  seconds.limit = seconds.limit,
  "data.table::fwrite" = {
    data.table::fwrite(input.df, tempfile(), showProgress = FALSE)
  },
  "pandas::to_csv" = {
    input_df_pd$to_csv(file_path, index = FALSE)
  }
)
```

```{r,warning=FALSE,message=FALSE}
refs.write.vary.cols <- atime::references_best(atime.write.vary.cols)

png("refs.write.vary.cols.png")
plot(refs.write.vary.cols)+
  labs(title = "refs.write.vary.cols")
dev.off()

plot(refs.write.vary.cols)
png()
print(refs.write.vary.cols)
ggsave("refs.write.vary.cols", refs.write.vary.cols, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

refs.write.vary.cols
plot(refs.write.vary.cols)
```


```{r,warning=FALSE,message=FALSE}
pred.write.vary.cols <- predict(refs.write.vary.cols)

png("pred.write.vary.cols.png")
plot(pred.write.vary.cols)+
  labs(title = "pred.write.vary.cols")
dev.off()


plot(pred.write.vary.cols)
```

```{r}
gg.write.dt.pd <- plot(pred.write.vary.cols) +
  theme(text = element_text(size = 15)) +
  ggtitle(sprintf("Write real numbers to CSV, \nwith pandas in Python \nand data.table in R, \n%d x N", n.rows)) +
  scale_x_log10("N = number of columns to write") +
  scale_y_log10("Computation time (seconds)\nmedian line, min/max band\nover 10 timings") +
  facet_null() +
  scale_fill_manual(values = write.colors) +
  scale_color_manual(values = write.colors)
```


```{r}
plot(pred.write.vary.cols)

png("gg.write.dt.pd")
plot(gg.write.dt.pd)+
  labs(title = "gg.write.dt.pd")
dev.off()

print(gg.write.dt.pd)
```


# Example 2: Reading a CSV File with data.table::fread() and pandas::read_csv()


## Comparison code

```{r,warning=FALSE,message=FALSE}
read.colors <- c(
  "data.table::fread" = "#D6604D",
  "pandas::read_csv" = "#BF812D"
)
n.rows <- 100
seconds.limit <- 10
file_path = 'data.csv'
atime.read <- atime::atime(
  N = as.integer(10^seq(2, 15, by = 0.2)),
  setup = {
    set.seed(1)
    input.vec <- rnorm(n.rows*N)
    input.mat <- matrix(input.vec, n.rows, N)
    input.df <- data.frame(input.mat)
    input.csv <- tempfile()
    fwrite(input.df, "data.csv")

    pd <- import("pandas")
    input_df_pd <- pd$DataFrame(input.df) 
  },
  seconds.limit = seconds.limit,
  "data.table::fread" = {
    data.table::fread("data.csv", showProgress = FALSE) 
  },
  "pandas::read_csv" = {
    pd <- import("pandas")
    reticulate::py_run_string("import pandas as pd")
    reticulate::py_run_string("pd.read_csv(file_path)")  
  }
)
```


```{r,warning=FALSE,message=FALSE}
refs.read.vary.cols <- atime::references_best(atime.read)


png("refs.read.vary.cols.png")
plot(refs.read.vary.cols)+
  labs(title = "refs.read.vary.cols")
dev.off()

png()
print(refs.read.vary.cols)
ggsave("refs.read.vary.cols", refs.read.vary.cols, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

refs.read.vary.cols
plot(refs.read.vary.cols)
```


```{r,warning=FALSE,message=FALSE}
pred.read.vary.cols <- predict(refs.read.vary.cols)

png("pred.read.vary.cols.png")
plot(pred.read.vary.cols.cols)+
  labs(title = "pred.read.vary.cols")
dev.off()

png()
print(pred.read.vary.cols)
ggsave("pred.read.vary.cols", pred.read.vary.cols, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

pred.read.vary.cols
plot(pred.read.vary.cols)
```



```{r,warning=FALSE,message=FALSE}
gg.read.pd <- plot(pred.read.vary.cols)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Read real numbers to CSV, \nwith pandas in Python \nand data.table in R, \n%d x N", n.rows))+
  scale_x_log10("N = number of columns to write")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=read.colors)+
  scale_color_manual(values=read.colors)
```

```{r,warning=FALSE,message=FALSE}
plot(gg.read.pd)

png("gg.read.pd.png")
plot(gg.read.pd)+
  labs(title = "gg.read.pd")
dev.off()

png()
print(gg.read.pd)
ggsave("gg.read.pd", gg.read.pd, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

gg.read.pd
```




# Example 3. Reshape performance comparison.

## A.	wide to long reshape.

## Comparison code
## data.table::melt() is faster

```{r,warning=FALSE,message=FALSE,results='hide'}

ml.colors <- c(
  "data.table::melt"="#D6604D",
  "pandas::pd.melt" = "#BF812D"
  )
n.folds <- 10
n.rows <- 100
seconds.limit <- 10

ml.reshape.atime <- atime::atime(
  N=as.integer(10^seq(2, 15, by=0.2)),
  setup={
    df <- data.frame(
      id = rep(1:N, each = 2),
      category = rep(c("A", "B"), N),
      value = rnorm(2 * N)
      )
    },
  seconds.limit= seconds.limit,
  
  "data.table::melt" = {
    data.table::melt(data.table(df), id.vars = c("id",  "category"),variable.names="variable", value.name = "value")
  },
  "pandas::pd.melt" = {
    py_df <- reticulate::r_to_py(df)
    pd <- import("pandas")
    pd$melt(py_df, id_vars = c("id", "category"), value_name = "score")  
  }
  )

```

```{r,warning=FALSE,message=FALSE}
ml.reshape.refs <- atime::references_best(ml.reshape.atime)

png()
print(ml.reshape.refs)
ggsave("ml.reshape.refs", ml.reshape.refs, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.reshape.refs
plot(ml.reshape.refs)
```



```{r,warning=FALSE,message=FALSE}
ml.reshape.pred <- predict(ml.reshape.refs)

png()
print(ml.reshape.pred)
ggsave("ml.reshape.pred", ml.reshape.pred, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.reshape.pred

plot(ml.reshape.pred)
```


```{r,warning=FALSE,message=FALSE}
ml.wide2long.pd <- plot(ml.reshape.pred)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Reshaping from wide \nto long panda & data.table \nover real numbers, \nN times", n.folds))+
  scale_x_log10("N = number of Mean,SD,Length to compute")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=ml.colors)+
  scale_color_manual(values=ml.colors)
```

```{r, warning=FALSE, message=FALSE}
png()
print(ml.wide2long.pd)
ggsave("ml.wide2long.pd", ml.wide2long.pd, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.wide2long.pd
plot(ml.wide2long.pd)
```



## B. long to wide reshape


## Comparison code



```{r,warning=FALSE,message=FALSE,results='hide'}

ml.colors <- c(
  "data.table::dcast" = "#D6604D",
  "pandas::pivot_table" = "#BF812D"
)

n.folds <- 10
n.rows <- 100
seconds.limit <- 1

ml.long2wide.atime <- atime::atime(
  N=as.integer(10^seq(2, 7, by=0.2)),
  setup={
    df <- data.frame(
      id = rep(1:N, each = 2),
      category = rep(c("A", "B"), N),
      value = rnorm(2 * N)
      )
    },
  seconds.limit= seconds.limit,
  "data.table::dcast" = {
    data.table::dcast(data.table(df), id ~ category, value.var = "value")
  },
  "pandas::pivot_table" = {
    py_df <- reticulate::r_to_py(df)
    pd <- import("pandas")
    pd$pivot_table(py_df, values = "value", index = "id", columns = "category")
  }
  )

```



```{r,warning=FALSE,message=FALSE}
ml.long2wide.refs <- atime::references_best(ml.long2wide.atime)

png()
print(ml.long2wide.refs)
ggsave("ml.long2wide.refs", ml.long2wide.refs, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.long2wide.refs

plot(ml.long2wide.refs)
```
 

```{r,warning=FALSE,message=FALSE}
ml.long2wide.pred <- predict(ml.long2wide.refs)

png()
print(ml.long2wide.pred)
ggsave("ml.long2wide.pred", ml.long2wide.pred, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.long2wide.pred

plot(ml.long2wide.pred)
```


```{r,warning=FALSE,message=FALSE}
ml.long2wide <- plot(ml.long2wide.pred)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Reshaping from \nlong to wide over real numbers, \nN times", n.folds))+
  scale_x_log10("N = number of Mean,SD,Length to compute")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=ml.colors)+
  scale_color_manual(values=ml.colors)

```

```{r,warning=FALSE,message=FALSE}
plot(ml.long2wide)

png()
print(ml.long2wide)
ggsave("ml.long2wide", ml.long2wide, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

ml.long2wide
```
